services:
  microfront-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4300:4300"
    environment:
      - CHOKIDAR_USEPOLLING=true

  microfront-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "80:80"